degrades gracefully if LOCALISE_SQL not set

diff --git a/sync_dev_website b/sync_dev_website
--- a/sync_dev_website
+++ b/sync_dev_website
@@ -26,7 +26,7 @@ if [ -z "$NAME" ]; then echo NAME is not set in config file; exit $E_CONFIGFAIL;
 if [ -z "$DATABASE" ]; then echo DATABASE is not set in config file; exit $E_CONFIGFAIL; fi
 if [ -z "$REMOTEMYSQLCNF" ]; then echo REMOTEMYSQLCNF is not set in config file; exit $E_CONFIGFAIL; fi
 if [ -z "$SERVER" ]; then echo SERVER is not set in config file; exit $E_CONFIGFAIL; fi
-if [ -z "$LOCALISE_SQL" ]; then echo LOCALISE_SQL is not set in config file; exit $E_CONFIGFAIL; fi
+
 
 
 
@@ -79,13 +79,19 @@ mysql --defaults-extra-file=$MYSQLCNF $DATABASE < /tmp/latest.$$.sql || {
 	}
 }
 
-echo "updating local database to point to itself"
-mysql --defaults-file=$MYSQLCNF $DATABASE < "$HOME/.sync_dev_website/$LOCALISE_SQL" || {
-	echo "can't update local database to point to -dev"
-	exit $E_UPDATEFAIL
-}
 
-echo "live database downloaded and installed to dev"
+if [ -z "$LOCALISE_SQL" ]; then 
+	echo "LOCALISE_SQL is not set in config file"
+ 	echo "Making the assumption that you're over-riding siteurl and home in wp-config.php"
+else
+	echo "updating local database to point to itself"
+	mysql --defaults-file=$MYSQLCNF $DATABASE < "$HOME/.sync_dev_website/$LOCALISE_SQL" || {
+		echo "can't update local database to point to -dev"
+		exit $E_UPDATEFAIL
+	}
+
+	echo "live database downloaded and installed to dev"
+fi
 
 if [ -z $FURNITUREDIR ] ; then 
 	echo "no furniture directory set in config file"
