now compressing remote database before scp-ing it

diff --git a/sync_dev_website b/sync_dev_website
--- a/sync_dev_website
+++ b/sync_dev_website
@@ -39,14 +39,20 @@ ssh $SERVER . $REMOTEBIN/dumplive.sh || {
 }
 
 echo "compressing database"
-ssh $SERVER "touch $REMOTEBIN/hello" || {
+ssh $SERVER "gzip -cf $DUMPFILE > /tmp/$NAME.dumpfile.gz" || {
 	echo "can't compress database on remote" >&2
 	exit $E_REMOTEFAIL
 }
 
-echo "copying database from $REMOTEDIR to /tmp/latest.$$.sql"
-scp $SERVER:$DUMPFILE /tmp/latest.$$.sql || {
+echo "copying database from /tmp/$NAME_dumpfile.gz to /tmp/latest.$$.sql.gz"
+scp $SERVER:/tmp/$NAME.dumpfile.gz /tmp/latest.$$.sql.gz || {
 	echo "can't copy from remote to local"
+	exit $E_COPYFAIL
+}
+
+echo "uncompressing database" 
+gunzip /tmp/latest.$$.sql.gz || {
+	echo "can't uncompress local copy of database"
 	exit $E_COPYFAIL
 }
 
