commented out image download code, as we always use an .htaccess rewrite these days

diff --git a/sync_dev_website b/sync_dev_website
--- a/sync_dev_website
+++ b/sync_dev_website
@@ -3,6 +3,13 @@
 # Pulls a copy of the WordPress database to your local machine, together with any assets
 # Config files live in ~/.sync_dev_website/
 
+# TODO:
+# - use GNU getopt to accept long arguments
+# - put in a package management system to enforce GNU getopt
+# - ? rewrite in a friendlier language 
+# - accept long arguments to 
+# 	- not do image downloading
+# 	- (other stuff)
 
 E_REMOTEFAIL=80
 E_COPYFAIL=81
@@ -43,7 +50,7 @@ if [ -z $MYSQLCNF ]; then
 fi
 
 
-echo connecting to $SERVER
+echo connecting to $DATASERVER
 
 echo "dumping live database"
 ssh $DATASERVER "mysqldump --defaults-file=$REMOTEMYSQLCNF $DATABASE > $DUMPFILE" || {
@@ -70,6 +77,7 @@ gunzip /tmp/latest.$$.sql.gz || {
 }
 
 echo "replacing local database"
+echo "trying command mysql --defaults-extra-file=$MYSQLCNF $DATABASE < /tmp/latest.$$.sql"
 mysql --defaults-extra-file=$MYSQLCNF $DATABASE < /tmp/latest.$$.sql || {
 	echo "can't import live db dump into local db"
 	echo "trying to start MAMP and see if that solves the problem"
@@ -93,30 +101,34 @@ else
 	echo "live database downloaded and installed to dev"
 fi
 
-if [ -z $FURNITUREDIR ] ; then 
-	echo "no furniture directory set in config file"
-else
-	echo "site configured to use furniture images; downloading them"
-	rsync -avh $SERVER:"$REMOTEDIR/furniture/" "$FURNITUREDIR" || {
-		echo "can't pull furniture from remote to local"
-		exit $E_ASSETSFAIL
-	}
-fi
+# 
+# commenting this out because we now check on staging for any images that can't be found locally
+# so no real point bringing down 100s of images.
+#
+# if [ -z $FURNITUREDIR ] ; then 
+# 	echo "no furniture directory set in config file"
+# else
+# 	echo "site configured to use furniture images; downloading them"
+# 	rsync -avh $SERVER:"$REMOTEDIR/furniture/" "$FURNITUREDIR" || {
+# 		echo "can't pull furniture from remote to local"
+# 		exit $E_ASSETSFAIL
+# 	}
+# fi
 
-if [ -z $REMOTE_ASSETS_DIR ] ; then
-	echo "no remote assets directory set in config file"
-	echo "falling back to $REMOTEDIR/wp-content/uploads"
-	rsync -avh $SERVER:"$REMOTEDIR/wp-content/uploads" "$LOCALDIR/wp-content" || {
-		echo "can't pull assets from remote to local"
-		exit $E_ASSETSFAIL
-	}
-else
-	echo "site configured to use assets outside of main wp-content folder; downloading them"
-	rsync -avh $SERVER:"$REMOTE_ASSETS_DIR" "$LOCAL_ASSETS_DIR" || {
-		echo "can't pull assets from remote to local"
-		exit $E_ASSETSFAIL
-	}
-fi
+# if [ -z $REMOTE_ASSETS_DIR ] ; then
+# 	echo "no remote assets directory set in config file"
+# 	echo "falling back to $REMOTEDIR/wp-content/uploads"
+# 	rsync -avh $SERVER:"$REMOTEDIR/wp-content/uploads" "$LOCALDIR/wp-content" || {
+# 		echo "can't pull assets from remote to local"
+# 		exit $E_ASSETSFAIL
+# 	}
+# else
+# 	echo "site configured to use assets outside of main wp-content folder; downloading them"
+# 	rsync -avh $SERVER:"$REMOTE_ASSETS_DIR" "$LOCAL_ASSETS_DIR" || {
+# 		echo "can't pull assets from remote to local"
+# 		exit $E_ASSETSFAIL
+# 	}
+# fi
 
 
 
